### ISSUE TITLE
Node as JS interpreter

### ISSUE THREAD

**Issue by nils-werner** [drwilly/clicknload2text#3]
Rhino is a somewhat exotic requirement, and I have found Node to be a suitable and more common replacement:

    js_cmd = ["node", "-e", script + "; console.log(f());"]

**Comment by drwilly** [comment]
Making the JS evaluation code a little more flexible is certainly a good idea.
Not sure about changing the default. Users probably have to modify the script anyway.
Ideally cnl2txt would detect usable JS interpreters dynamically.

**Comment by drwilly** [comment]
resolved as of ee86f0265a2486f85035918dc9f8b50a4336fd4f
