### ISSUE TITLE
code 500, message [WinError 2] The system cannot find the file specified on 

### ISSUE THREAD

**Issue by selimovd** [drwilly/clicknload2text#4]
Hello,

very good idea with this program, I really need that because I just need the links and don't want to install any other program.

I changed the script from Rhino to NodeJS. NodeJS is also installed.

When I try to grab a link the program shows the following:

`127.0.0.1 - - [05/May/2019 15:23:37] "GET /jdcheck.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 15:23:37] "GET /jdcheck.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 15:23:38] "GET /jdcheck.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 15:23:38] "GET /jdcheck.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 15:23:38] "POST /flash/addcrypted2 HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2019 15:23:39] code 500, message [WinError 2] The system cannot find the file specified
127.0.0.1 - - [05/May/2019 15:23:39] "POST /flash/addcrypted2 HTTP/1.1" 500 -`

What am I missing or why is the error appearing?

Thanks and best regards

**Comment by drwilly** [comment]
Unfortunately I do not have a windows system to test, but it seems like the program cannot find the node executable.
Is `node` in your `PATH`?
Otherwise you can try to specify the full path, like `C:\full\path\to\node`.

**Comment by selimovd** [comment]
Yes, node is in my path and also python.
I don't really understand which "file" he cannot find.

I tried to debug, but I didn't do much in Python and the Click'n'Load Window is closing too fast do debug. Is there any other way I can debug or help to investigate this case?

**Comment by drwilly** [comment]
Well, there are only two external programs run by cnl2txt: the js-interpreter (`rhino`, `node`, ...) and `openssl`

As for the window closing, you should be able to open a terminal yourself and start cnl2txt from there.

**Comment by selimovd** [comment]
Thank you very much! The problem was between the keyboard and the chair...
I forgot to add openssl to the PATH
